import type { AppState } from "@/lib/types";

export const demoState: AppState = {
  clients: [
    {
      id: "client-demo",
      name: "Clube Carvão",
      slug: "clube-carvao",
      password: "clube123",
      subtitle: "Dashboard demonstrativo de campanhas, públicos e criativos",
      createdAt: new Date().toISOString(),
      goals: {
        maxCpl: 30,
        maxCostPerMessage: 15,
        maxSpendWithoutResult: 100,
        maxFrequency: 2.5,
        minCtr: 1,
      },
    },
    {
      id: "client-guto",
      name: "Guto",
      slug: "guto",
      password: "guto123",
      subtitle: "Dashboard demonstrativo de vendas, ROAS e lucro",
      createdAt: new Date().toISOString(),
      goals: {
        targetRoas: 1.2,
        maxCpa: 90,
        maxCpl: 25,
        maxSpendWithoutResult: 120,
      },
    },
  ],
  imports: [
    {
      id: "import-demo-clube-campaigns",
      clientId: "client-demo",
      fileName: "CA---Clube-Carvao-Campanhas-Abril-2026.csv",
      level: "campaign",
      periodStart: "2026-04-01",
      periodEnd: "2026-04-30",
      importedAt: new Date().toISOString(),
      rowCount: 3,
      columns: ["Nome da campanha", "Resultados", "Valor usado (BRL)", "Indicador de resultados"],
    },
    {
      id: "import-demo-guto-campaigns",
      clientId: "client-guto",
      fileName: "CA---Guto-Campanhas-Abril-2026.csv",
      level: "campaign",
      periodStart: "2026-04-01",
      periodEnd: "2026-04-30",
      importedAt: new Date().toISOString(),
      rowCount: 3,
      columns: ["Nome da campanha", "Compras", "GRANA NO BOLSO", "ROAS"],
    },
  ],
  mappings: [],
  rows: [
    {
      id: "demo-clube-1",
      importId: "import-demo-clube-campaigns",
      clientId: "client-demo",
      level: "campaign",
      entityName: "Forms Nat CBO Validados",
      periodStart: "2026-04-01",
      periodEnd: "2026-04-30",
      status: "active",
      resultIndicator: "actions:leadgen.other",
      objective: "lead",
      raw: {},
      spend: 2072.8,
      results: 51,
      costPerResult: 40.64,
      impressions: 102728,
      reach: 49969,
      frequency: 2.06,
      cpm: 20.18,
      linkClicks: 1294,
      purchases: 0,
      checkouts: 0,
      landingPageViews: 0,
      roas: 0,
      profit: 0,
      revenue: 0,
    },
    {
      id: "demo-clube-2",
      importId: "import-demo-clube-campaigns",
      clientId: "client-demo",
      level: "campaign",
      entityName: "WPP RMKT Depoimentos",
      periodStart: "2026-04-01",
      periodEnd: "2026-04-30",
      status: "active",
      resultIndicator: "actions:onsite_conversion.messaging_conversation_started_7d",
      objective: "message",
      raw: {},
      spend: 681.57,
      results: 39,
      costPerResult: 17.48,
      impressions: 35379,
      reach: 14386,
      frequency: 2.46,
      cpm: 19.26,
      linkClicks: 218,
      purchases: 0,
      checkouts: 0,
      landingPageViews: 0,
      roas: 0,
      profit: 0,
      revenue: 0,
    },
    {
      id: "demo-clube-3",
      importId: "import-demo-clube-campaigns",
      clientId: "client-demo",
      level: "ad",
      entityName: "Criativo Karen",
      parentName: "[SÃO PAULO E INTERIOR] [+22] [SEGUIDORES]",
      periodStart: "2026-04-01",
      periodEnd: "2026-04-30",
      status: "not_delivering",
      resultIndicator: "actions:onsite_conversion.messaging_conversation_started_7d",
      objective: "message",
      raw: {},
      spend: 183.51,
      results: 9,
      costPerResult: 20.39,
      impressions: 1691,
      reach: 813,
      frequency: 2.08,
      cpm: 108.52,
      linkClicks: 18,
      purchases: 0,
      checkouts: 0,
      landingPageViews: 0,
      roas: 0,
      profit: 0,
      revenue: 0,
      qualityRanking: "Na média",
      engagementRanking: "Na média",
      conversionRanking: "Abaixo da média",
    },
    {
      id: "demo-guto-1",
      importId: "import-demo-guto-campaigns",
      clientId: "client-guto",
      level: "campaign",
      entityName: "RMKT [WEB] [IMGS]",
      periodStart: "2026-04-01",
      periodEnd: "2026-04-30",
      resultIndicator: "actions:offsite_conversion.fb_pixel_purchase",
      objective: "sales",
      raw: {},
      spend: 1277.93,
      results: 18,
      costPerResult: 71,
      impressions: 74779,
      reach: 0,
      frequency: 0,
      cpm: 17.09,
      linkClicks: 859,
      purchases: 18,
      checkouts: 63,
      landingPageViews: 685,
      roas: 1.22,
      profit: 277.27,
      revenue: 1555.2,
    },
    {
      id: "demo-guto-2",
      importId: "import-demo-guto-campaigns",
      clientId: "client-guto",
      level: "campaign",
      entityName: "07/04 [NATIVES] [IMERSÃO]",
      periodStart: "2026-04-01",
      periodEnd: "2026-04-30",
      resultIndicator: "actions:leadgen.other",
      objective: "lead",
      raw: {},
      spend: 969.41,
      results: 228,
      costPerResult: 4.25,
      impressions: 37998,
      reach: 0,
      frequency: 0,
      cpm: 25.51,
      linkClicks: 881,
      purchases: 0,
      checkouts: 0,
      landingPageViews: 1,
      roas: 0,
      profit: -969.41,
      revenue: 0,
    },
  ],
};
